### ISSUE TITLE
大佬，问几个关于代码的小问题，可否帮忙解答一下？

### ISSUE THREAD

**Issue by 122al** [zhucaidan/btpanel-v7.7.0#3]
大佬，想问几个问题 

1. 这个BT原版脚本里面

`LIBCURL_VER=$(dpkg -l|grep libcurl4|awk '{print $3}')
	if [ "${LIBCURL_VER}" == "7.68.0-1ubuntu2.8" ];then
		apt-get remove libcurl4 -y
		apt-get install curl -y
	fi`
这些代码感觉是判断版本号然后安装插件的，我看你的脚本里面删掉了，是这两个插件没有用么？
`	chmod -R 700 $pyenv_path/pyenv/bin
	/www/server/panel/pyenv/bin/pip3 install flask -U
	/www/server/panel/pyenv/bin/pip3 install flask-sock`
这两行插件代码也删掉了。

2. ![](http://img.11.wf/i/2022/03/31/6245661a2f12e.png)

然后这行脚本里面感觉好像少了一个变量符号。

3. `Run_User="www"
	wwwUser=$(cat /etc/passwd|grep www)
	if [ "${wwwUser}" == "" ];then
		groupadd ${Run_User}
		useradd -s /sbin/nologin -g ${Run_User} ${Run_User}
	fi`
这几行代码删掉了，是不是意味着宝塔的面板是直接以root权限运行了？在面板里面的操作好多我看都是www权限的，会不会出现权限的问题啊？

4. public.sh脚本里面添加了一个init_check()这个方法，但是好像没有被调用，是有什么别的用处么？

**Comment by zhucaidan** [comment]
你看的”BT原版脚本“是哪个宝塔版本？以上的脚本在备份官方7.7的脚本时候，原始代码就是这样的

**Comment by 122al** [comment]
额 。。。就是现在官网的脚本...

**Comment by zhucaidan** [comment]
> 额 。。。就是现在官网的脚本...

现在官网版本是7.9.0，我这个是7.7.0，我不知道你对比的意义是什么？

**Comment by 122al** [comment]
> > 额 。。。就是现在官网的脚本...
> 
> 现在官网版本是7.9.0，我这个是7.7.0，我不知道你对比的意义是什么？

就是看看大概脚本有什么改动。7.9与7.7也只是版本的安装不同，环境检查配置应该不会有很大的变动吧。我说的几个问题都没涉及到update6.sh这个文件，这个脚本应该才是7.9的安装文件。。我以为是你精简的，就是想咨询下是不是那些不一样的都没用什么用处 给精简掉了而已。

**Comment by zhucaidan** [comment]
> > > 额 。。。就是现在官网的脚本...
> 
> > 
> 
> > 现在官网版本是7.9.0，我这个是7.7.0，我不知道你对比的意义是什么？
> 
> 
> 
> 就是看看大概脚本有什么改动。7.9与7.7也只是版本的安装不同，环境检查配置应该不会有很大的变动吧。我说的几个问题都没涉及到update6.sh这个文件，这个脚本应该才是7.9的安装文件。。我以为是你精简的，就是想咨询下是不是那些不一样的都没用什么用处 给精简掉了而已。

没有做任何官方7.7.0改动，宝塔自从7.8.0之后做了大改动，包括底层架构和安装方法等等，导致到现在也没有被干净破解登录提示框，7.9.0也做了很大范围改动，已经和7.7.0代码有太多不同
