### ISSUE TITLE
已经失效

### ISSUE THREAD

**Issue by GoodManWEN** [zhucaidan/btpanel-v7.7.0#4]
近期安装已被强制绑定

**Comment by zhucaidan** [comment]
> 近期安装已被强制绑定

官方7.7.0本来就要绑定手机号，自行搜索7.7.0怎么跳过绑定

**Comment by GoodManWEN** [comment]
> > 近期安装已被强制绑定
> 
> 官方7.7.0本来就要绑定手机号，自行搜索7.7.0怎么跳过绑定

之前执行了 rm -rf /www/server/panel/data/bind.pl 不知道为什么绑定界面还在，最近重新执行了rm -f /www/server/panel/data/bind.pl 又成功跳过绑定了

**Comment by GoodManWEN** [comment]
另外我看了一下，我的770面板里网站ssl证书有不显示到期时间的bug，显示的都是永久，查了一下最新版本里似乎续签的代码改了一些

**Comment by zhucaidan** [comment]
执行完解除绑定命令要在浏览器ctrl+f5清空缓存，证书的问题我用chrome浏览器没发现，你可以试一下第三方的一年证书会不会显示时间
